kind: pipeline
name: default

steps:
- name: compile
  image: rust
  environment:
    token:
      from_secret: token
  commands:
  - cargo install mdbook
  - ./ci.sh compile
  - ./ci.sh deploy
- name: flush-dns
  image: git.duguying.net/duguying/qcloud-dns-tool
  commands:
  - qcloud-dns-tool -p "https://parsing-techniques.duguying.net/"
  environment:
    SecretId:
      from_secret: qcloud_sid
    SecretKey:
      from_secret: qcloud_skey
